// Resume Data
export const NOTES_DATA_REQUEST = "NOTES_DATA_REQUEST";
export const NOTES_DATA_FAILURE = "NOTES_DATA_FAILURE";


export const POST_NOTES_DATA_SUCCESS = "POST_NOTES_DATA_SUCCESS";
export const GET_NOTES_DATA_SUCCESS = "GET_NOTES_DATA_SUCCESS";
export const DELETE_NOTES_DATA_SUCCESS = "DELETE_NOTES_DATA_SUCCESS";



// Authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";


// Signup
export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE = "USER_FAILURE";
export const USER_SUCCESS = "USER_SUCCESS";